use_frameworks!

platform :ios, '9.0'

target 'TZXingObjC_Example' do
  pod 'TZXingObjC', :git => 'git@github.com:fish-yan/TZXingObjC.git'

  target 'TZXingObjC_Tests' do
    inherit! :search_paths

    
  end
end
